{
 "title": "Aggregator dashboard",
 "description": "Dashboard with statistics on several ADS-B aggregators.",
 "tags": [
  "ads-b",
  "aggregators"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Dashboard Info",
   "type": "text",
   "gridPos": { "h": 2.3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div align=\"center\">\n  <a href=\"https://github.com/rickstaa/adsb-dashboards\" target=\"_blank\"><img alt=\"GitHub Repo stars\" src=\"https://img.shields.io/github/stars/rickstaa/adsb-dashboards?style=social\"></a>\n  <a href=\"https://github.com/rickstaa/adsb-dashboards/fork\" target=\"_blank\"><img alt=\"GitHub forks\" src=\"https://img.shields.io/github/forks/rickstaa/adsb-dashboards?style=social\"></a>\n</div>"
   }
  },
  {
   "title": "MLAT Feeders",
   "type": "timeseries",
   "description": "Aggregator MLAT Feeder count.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2.3 },
   "targets": [
    { "expr": "mlat_feeders", "legendFormat": "{{aggregator}}" }
   ]
  },
  {
   "title": "BEAST Feeders",
   "type": "timeseries",
   "description": "Aggregator BEAST Feeder count.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2.3 },
   "targets": [
    { "expr": "beast_feeders", "legendFormat": "{{aggregator}}" }
   ]
  },
  {
   "title": "Other Feeders",
   "type": "timeseries",
   "description": "Aggregator combined ACARS, VDL, HFDL, and SATCOM feeder count.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11.3 },
   "targets": [
    { "expr": "other_feeders", "legendFormat": "{{aggregator}}" }
   ]
  },
  {
   "title": "Aircraft",
   "type": "timeseries",
   "description": "Aggregator aircraft count.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11.3 },
   "targets": [
    { "expr": "aircraft", "legendFormat": "{{aggregator}}" }
   ]
  }
 ]
}